---

access_token: myaccesstoken
url: https://gitlab.privateinstance.com
policies:
- name: nonsemverpolicy
  filter:
    include: .*
    exclude: ^v.+
    keep: 5
    age: 30
repositories:
- project: 123
  image: myproject/somerepository
  policies:
  - nonsemverpolicy
