---

access_token: myaccesstoken
url: https://gitlab.privateinstance.com
repositories:
- project: 123
  image: myproject/somerepository
  filter:
    include: .*
    exclude: v.+
    keep: 5
    age: 30